package com.example.runitup.mobile.service

import com.example.runitup.mobile.repository.RunSessionEventRepository
import com.example.runitup.mobile.rest.v1.dto.*
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import org.mockito.kotlin.argumentCaptor
import org.mockito.kotlin.mock
import org.mockito.kotlin.verify

class RunSessionEventLoggerTest {

    private val repo: RunSessionEventRepository = mock()
    private val logger = RunSessionEventLogger(repo)

    @Test
    fun `log should build RunSessionEvent with all fields and save it`() {
        // Given
        val sessionId = "session-123"
        val action = RunSessionAction.USER_JOINED
        val actor = Actor(type = ActorType.USER, id = "user-42")
        val subjectUserId = "user-99"
        val reason = "Joined via invite link"
        val metadata = mapOf(
            "partySize" to "2",
            "source" to "iOS"
        )
        val prevStatus = "PENDING"
        val newStatus = "CONFIRMED"
        val correlationId = "corr-abc"
        val idempotencyKey = "idem-123"

        val captor = argumentCaptor<RunSessionEvent>()

        // When
        logger.log(
            sessionId = sessionId,
            action = action,
            actor = actor,
            subjectUserId = subjectUserId,
            reason = reason,
            metadata = metadata,
            prevStatus = prevStatus,
            newStatus = newStatus,
            correlationId = correlationId,
            idempotencyKey = idempotencyKey
        )

        // Then
        verify(repo).save(captor.capture())

        val saved = captor.firstValue

        // id is generated by Mongo later; logger does not set it
        assertNull(saved.id, "Logger should not set id explicitly")

        assertEquals(sessionId, saved.sessionId)
        assertEquals(action, saved.action)
        assertEquals(actor, saved.actor)
        assertEquals(subjectUserId, saved.subjectUserId)
        assertEquals(reason, saved.reason)
        assertEquals(metadata, saved.metadata)
        assertEquals(prevStatus, saved.prevStatus)
        assertEquals(newStatus, saved.newStatus)
        assertEquals(correlationId, saved.correlationId)
        assertEquals(idempotencyKey, saved.idempotencyKey)

        // ts is assigned by default (Instant.now()) in the data class
        assertNotNull(saved.ts, "ts should be auto-populated by RunSessionEvent default")
    }

    @Test
    fun `log should handle minimal call with only required fields`() {
        // Given
        val sessionId = "session-456"
        val action = RunSessionAction.SESSION_CREATED
        val actor = Actor(type = ActorType.SYSTEM, id = null)

        val captor = argumentCaptor<RunSessionEvent>()

        // When
        logger.log(
            sessionId = sessionId,
            action = action,
            actor = actor
            // everything else left as default null
        )

        // Then
        verify(repo).save(captor.capture())

        val saved = captor.firstValue

        // Required fields
        assertEquals(sessionId, saved.sessionId)
        assertEquals(action, saved.action)
        assertEquals(actor, saved.actor)

        // Optional fields should be null by default
        assertNull(saved.subjectUserId)
        assertNull(saved.reason)
        assertNull(saved.metadata)
        assertNull(saved.prevStatus)
        assertNull(saved.newStatus)
        assertNull(saved.correlationId)
        assertNull(saved.idempotencyKey)

        // id is still null before persistence
        assertNull(saved.id)

        // ts still should be set
        assertNotNull(saved.ts, "ts should be auto-populated even for minimal calls")
    }
}
