package com.example.runitup.mobile.enum

enum class PushTrigger(val key: String) {
    RUN_SESSION_CONFIRMED("RUN_SESSION_CONFIRMED"),
    RUN_SESSION_CANCELLED("RUN_SESSION_CANCELLED"),
    RUN_SESSION_USER_JOINED("RUN_SESSION_USER_JOINED"),
    RUN_SESSION_USER_JOINED_WAITLIST("RUN_SESSION_USER_JOINED_WAITLIST"),
    RUN_SESSION_BOOKING_CANCELLED("RUN_SESSION_BOOKING_CANCELLED"),
    RUN_SESSION_CREATED("RUN_SESSION_CREATED"),
    RUN_SESSION_BOOKING_CANCELLED_BY_USER("RUN_SESSION_BOOKING_CANCELLED_BY_USER")
}