name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read   # <-- important for using GITHUB_TOKEN to read packages (same-repo scenarios)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTOR: ${{ github.actor }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login to GHCR (container registry) – you're good here
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login  --username ngiyulu --password ${{ secrets.PASSWORD }} ghcr.io

      # Build image, passing GitHub Packages creds for Gradle
      # Prefer a PAT stored as secrets.GPR_TOKEN (scopes: read:packages; + repo if package is private)
      - name: Build image
        run: |
          docker build \
            --build-arg GPR_USER=${{ github.actor }} \
            --build-arg GPR_TOKEN=${{ secrets.PASSWORD }} \
            -t ghcr.io/ngiyulu/runitup:1.0.0 .

      - name: Push image
        run: docker push ghcr.io/ngiyulu/runitup:1.0.0